""" file containing all used constants

"""


EMAIL_SENDER = 'EMAIL_SENDER'
EMAIL_RECIPIENT = 'EMAIL_RECIPIENT'

EMAIL_ALERT_THRESHOLD = 'EMAIL_ALERT_THRESHOLD'
TEXT_ALERT_THRESHOLD = 'TEXT_ALERT_THRESHOLD'
TWEET_FREQUENCY = 'TWEET_FREQUENCY'

EMAIL_INTERVAL = 'EMAIL_INTERVAL'
FILTER_STRING = 'FILTER_STRING'
